services:
  caddy:
    image: caddy
    restart: always
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./_caddy/srv:/srv
      - ./_caddy/data:/data
      - ./_caddy/config:/config
