version: "3.9"
networks:
  caddy:
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
  me:
    container_name: me
    image: soltanireza65/me.rezasoltani.info:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - caddy

volumes:
  caddy_data:
    external: true
  caddy_config:
