services:
  caddy:
    image: caddy
    restart: always
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/srv:/srv
      - ./.caddy/data:/data
      - ./.caddy/config:/config
